name: Build & Test

on:
  pull_request:
    branches: [ develop ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v $(go list ./... | grep -v /internal/) # exclude internal

    - name: Test
      run: go test -v $(go list ./... | grep -v /internal/) # exclude internal
